name: CI/CD with Docker

# Menjalankan workflow setiap kali ada push atau pull request ke branch utama
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t your-image-name:latest .

      # Push Docker image ke Docker Hub (opsional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy aplikasi menggunakan Docker
      - name: Deploy Docker container
        run: |
          docker run -d -p 80:80 --name your-container-name your-image-name:latest
